###
POST http://localhost:8000/createOrder HTTP/1.1
Host: localhost:8000
Content-Type: application/json

{
    "id":"22222",
    "price": 500.80,
    "tax": 25.00
}

###
GET http://localhost:8000/order HTTP/1.1
Host: localhost:8000
Content-Type: application/json
